name: Deploy to Netlify
 
on:
  push:
    branches:
      - main
 
permissions:
  contents: read
  pages: write
  id-token: write
 
# concurrency:
#   group: "pages"
#   cancel-in-progress: false
 
jobs:
  # build:
  #   name: '🏗️ Build files'
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0 # Fetch all history for git info
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 22
  #     - name: Install Dependencies
  #       run: npm ci
  #     - name: Build Quartz
  #       run: npx quartz build
  #     - name: Upload artifact
  #       uses: actions/upload-pages-artifact@v3
  #       with:
  #         path: public
 
  # deploy:
  #   needs: build
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4

  deploy:
    name: '🚀 Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: jsmrcaga/action-netlify-deploy@v2.4.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'public'
          build_command: 'npx quartz build'