name: 'Netlify Preview Deploy'

on:
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  deploy:
    name: '🚀 Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Sets the branch name as environment variable
      - uses: nelonoel/branch-name@v1.0.1

      - uses: jsmrcaga/action-netlify-deploy@v2.3.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'public'
          build_command: 'npx quartz build'
          deploy_alias: ${{ env.BRANCH_NAME }}