name: Update Newest Files

on:
  schedule:
    - cron: "0 0 * * *"   # Run every day at midnight UTC
  workflow_dispatch:      # Allow manual trigger too
  push:
    branches:
      - main              # also run whenever commits are pushed to main

jobs:
  update-newest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0   # Important! We need full git history for `git log`

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Run newest-files script   # This will generate "~/newest-added-files.json" and "~/newest-modified-files.json"
        run: node scripts/run-update-newest-files.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add newest-files.json
          git commit -m "Update newest-files.json [ci skip]" || echo "No changes to commit"
          git push